services:
  mysql:
    image: 'mysql:8.4'
    container_name: mysql_container
    environment:
      - 'MYSQL_DATABASE=cep_db'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_USER=cep_user'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: